version: '3.3'
services:
  dbmate:
    image: ghcr.io/amacneil/dbmate
    command: --schema-file /tmp/rust-sense-schema.sql up
    environment:
      - DATABASE_URL=sqlite3:/app/data/state.sqlite
    volumes:
      - ./data:/app/data
      - ../../db/migrations/sqlite:/db/migrations
  app:
    depends_on:
      dbmate:
        condition: service_completed_successfully
    volumes:
      - ./credentials:/app/credentials
      - ./instances:/app/instances
      - ./authtokens:/app/authtokens
      - ./logs:/app/logs
      - ./maps:/app/maps
      - ./data:/app/data
    environment:
      - RPP_DISCORD_CLIENT_ID=111....1111
      - RPP_DISCORD_TOKEN=token
      - RPP_PERSISTENCE_ADAPTER=sqlite
      - RPP_SQLITE_PATH=/app/data/state.sqlite
    container_name: rust-sense
    image: ghcr.io/rust-sense/bot
