name: Docker image build

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main, develop ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  get-metadata:
    runs-on: ubuntu-latest

    if: github.event_name != 'pull_request'

    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      version: ${{ steps.meta.outputs.version }}
      json: ${{ steps.meta.outputs.json }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@418e4b98bf2841bd337d0b24fe63cb36dc8afa55
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=unstable,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
            type=semver,pattern={{version}}

  build-arch-manifest:
    strategy:
      fail-fast: true

      matrix:
        type:
          - linux-amd64
          - linux-arm64
        include:
          - type: linux-amd64
            docker-platform: linux/amd64
            runner: ubuntu-22.04
          - type: linux-arm64
            docker-platform: linux/arm64
            runner: arc-runner-rust-sense

    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    needs:
      - get-metadata

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login in registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@6d4b68b490aef8836e8fb5e50ee7b3bdfa5894f0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@21162887f0d6e25b4e8eafb0cf44cf9bf7f6acd3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          platforms: ${{ matrix.docker-platform }}
          labels: ${{ needs.get-metadata.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=${{ github.event_name != 'pull_request' }}

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.type }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-manifest:
    runs-on: ubuntu-latest

    if: github.event_name != 'pull_request'

    permissions:
      contents: read
      packages: write

    needs:
      - get-metadata
      - build-arch-manifest

    steps:
      - name: Create digests directory
        run: mkdir -p /tmp/digests

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login in registry ${{ env.REGISTRY }}
        uses: docker/login-action@6d4b68b490aef8836e8fb5e50ee7b3bdfa5894f0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        env:
          METADATA_JSON: "${{ needs.get-metadata.outputs.json }}"
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$METADATA_JSON") \
              $(find . -type f -printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%f ')

      - name: Inspect image
        run: docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.get-metadata.outputs.version }}
