name: Update from original repository

concurrency:
  group: sync-upstream
  cancel-in-progress: true

on:
  schedule:
  - cron: "0 0 * * 1"
  workflow_dispatch:

env:
  UPDATE_BRANCH: upstream-updates
  REMOTE_URL: https://github.com/alexemanuelol/rustplusplus
  REMOTE_BRANCH: master

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch all history for all branches and tags.
        # Required because otherwise there are always changes detected when executing diff/rev-list
        fetch-depth: 0

        # Always checkout develop, it's always going to be the target branch
        ref: "develop"

    - name: Init Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Main workflow
      id: main
      run: |
        echo "Adding remote upstream repo"
        git remote add upstream ${{ env.REMOTE_URL }}

        echo "Fetching remote upstream repo"
        git fetch upstream

        echo "Deleting local branch that will contain the updates - if present"
        git branch -D ${{ env.UPDATE_BRANCH }} || true

        echo "Checking if the remote upstream repo has new commits"
        git rev-list ..upstream/${{ env.REMOTE_BRANCH }}

        if [ $(git rev-list --count ..upstream/${{ env.REMOTE_BRANCH }}) -eq 0 ]; then
          echo "There are no commits new commits on the upstream repo"

          echo "Deleting origin branch that contains the updates - if present"
          git push -f origin --delete ${{ env.UPDATE_BRANCH }} || true

          echo "abort=1" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Found new commits on the upstream repo"

        echo "Creating update branch"
        git branch ${{ env.UPDATE_BRANCH }} upstream/${{ env.REMOTE_BRANCH }}
        git branch --unset-upstream ${{ env.UPDATE_BRANCH }}
        echo "abort=0" >> $GITHUB_OUTPUT

    - name: Push branch
      if: steps.main.outputs.abort == 0
      run: |
        echo "Pushing update branch"
        git push -f -u origin ${{ env.UPDATE_BRANCH }}

    - name: Create pull request
      if: steps.main.outputs.abort == 0
      run: |
        gh pr create \
          --base develop \
          --head ${{ env.UPDATE_BRANCH }} \
          --repo ${{ github.repository }} \
          --title 'New changes from upstream rustplusplus' \
          --body 'This is an automated PR to sync changes from the upstream rustplusplus repo into this one'
      env:
        GH_TOKEN: ${{ github.token }}
